Repository Project-Dahlia/Dahlia, pull requests merged in 2024-09, with the labels that each got.

#117 101 sub task load json file of available parking spots to postgressql
  README.md
  package-lock.json
  package.json
  packages/backend/package.json
  packages/backend/src/config/config.js
  packages/backend/src/config/database.js
  packages/backend/src/controller/home-controller.js
  packages/backend/src/data/toronto-parking-2019.json
  packages/backend/src/migrations/20240818201759-create-users-table.js
  packages/backend/src/migrations/20240912231028-create-parking-spots.js
  packages/backend/src/models/parkingspots.js
  packages/backend/src/seeders/loadParkingData.js
  packages/backend/tests/test-auth.js
  packages/backend/tests/testdb.js
Labels: 🚀 new feature, 🛠️ sub-task

#123 refactor(frontend): modularize map component for imporved scalibility
  packages/frontend/src/app/page.tsx
  packages/frontend/src/components/map/getposition.tsx
  packages/frontend/src/components/map/render.tsx
Labels: ✨ polish, 🗒️ request

#127 feat(frontend): add parking card
  package-lock.json
  packages/frontend/package.json
  packages/frontend/src/app/page.tsx
  packages/frontend/src/components/common/icons.tsx
  packages/frontend/src/components/common/parking-card/parkcard-wrapper.tsx
  packages/frontend/src/components/common/parking-card/parkcard.tsx
  packages/frontend/src/components/layout/auth-layout.tsx
  packages/frontend/src/components/map/getposition.tsx
  packages/frontend/src/components/ui/card.tsx
Labels: 🖼️ UI / UX
