Repository Project-Dahlia/Dahlia, pull requests merged in 2024-08, with the labels that each got.

#96 feat(frontend): reset and change password UI
  package-lock.json
  packages/frontend/__tests__/ChangePasswordForm.test.tsx
  packages/frontend/__tests__/UserAuthForm.test.tsx
  packages/frontend/package.json
  packages/frontend/src/app/api/auth/change-password/page.tsx
  packages/frontend/src/app/api/auth/login/page.tsx
  packages/frontend/src/app/api/auth/register/page.tsx
  packages/frontend/src/app/api/auth/reset-password/page.tsx
  packages/frontend/src/app/layout.tsx
  packages/frontend/src/components/change-password-form.tsx
  packages/frontend/src/components/logo.tsx
  packages/frontend/src/components/main-nav.tsx
  packages/frontend/src/components/ui/sonner.tsx
  packages/frontend/src/components/user-auth-form.tsx
  packages/frontend/src/lib/handlers/auth-handler.ts
  packages/frontend/src/lib/handlers/google-auth-handler.ts
  packages/frontend/src/lib/validation/auth.tsx
  packages/frontend/src/middleware.ts
Labels: 🖼️ UI / UX

#98 fix(frontend): enhance visibility and layout stability
  packages/frontend/__tests__/Header.test.tsx
  packages/frontend/src/components/main-nav.tsx
  packages/frontend/src/components/site-header.tsx
Labels: 🐛 bug, 🖼️ UI / UX

#100 feat(root): add subtask template for github use
  .github/ISSUE_TEMPLATE/subtask.yml
Labels: 🚀 new feature, ⚙️ setup, 📔 task / story
